### ISSUE TITLE
Reverse to objectid

### ISSUE THREAD

**Issue by Parables** [3imed-jaberi/Short-ObjectId#9]
I can shorten an object id with this which is perfect,now  how do I reverse it to get my ID back so I can do my findbyID?. README didn't give a clue

**Comment by 3imed-jaberi** [comment]
Thanks u @Parables, 
It didn't occur to me how to reverse 😅, sorry for that. I will provide this feature in few minutes 💯.

**Comment by 3imed-jaberi** [comment]
Available: https://www.npmjs.com/package/short-objectid/v/4.2.0
Example 🤖 : 

```javascript
const shortObjectId = require ('short-objectid') ; // v4.2.0
 let MongoDB_ObjectID = { "$oid" : "507f191e810c19729de860ea" },
config = { Timestamp: 57, MachineId: 65, ProcessId: 48, Counter: 47 },
// default opts is false (support old version ) 
opts = { cache: true };
 
// result : [shortObjectId, MongoDB_ObjectID]
let [
  shortObjectId, 
  MongoDB_ObjectID: _id // i rename MongoDB_ObjectID to _id
]= shortObjectId(MongoDB_ObjectID, config, opts);

// you can now use _id .. 

```

**Comment by 3imed-jaberi** [comment]
@Parables, this is [an example]( https://codesandbox.io/s/short-objectid-fs0kv) on sandbox with `express@4.17.1` and `mongoose@5.9.10` and the current version  of  `short-objectid@5.0.0 ` ..

**Comment by 3imed-jaberi** [comment]
@Parables, this is [an example]( https://codesandbox.io/s/short-objectid-fs0kv) on sandbox with `express@4.17.1` and `mongoose@5.9.10` and the current version  of  `short-objectid@5.0.0 ` .. 

> If you have any problem, plz don't hesitate to tell me ^^.

**Comment by Parables** [comment]
you are amazing, bro :+1:  .Its hard for me to believe that you were able to provide a slolution that quick. Really love your work. :heart:
